# Generated by Django 5.2 on 2025-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('imdb_rating', models.FloatField()),
                ('year', models.IntegerField()),
                ('poster_url', models.URLField()),
            ],
        ),
    ]
